### PR TITLE
[FIX] #192 - the heartbeat timer prevents nats.close() from existing Close now removes the timer if it was scheduled.

### PR DESCRIPTION
**Pull request by aricart**

### CODE REVIEW

**Comment by derekcollison** [comment]
+1 to a test.

**Comment by aricart** [comment]
"If we test it we may find other bugs"
Interestingly we don't seem to emit 'close'... This will require a few more calories/review.

**Comment by derekcollison** [comment]
We had tests that checked for close emit at some point.

**Comment by aricart** [comment]
@derekcollison the `close` event is propagated when the client disconnects from a server and has exhausted its retries). When initiated by a client calling `close()`, no notification is given because the code itself called it. I propose that we add a `closed` event that is used in a test. Alternatively, we can launch a subprocess and verify it exits.

**Comment by derekcollison** [comment]
We should do a test for exit like you suggest. Not sure on closed event when application calls close.

**Pull request merged**
