### PR TITLE
Port tokenHandler mechanism from go-nats (option processInbound())

### PR DESCRIPTION
**Pull request by andriy-bulynko**
Fixes: #265 

# Description

I wasn't sure of the best place to plug this in. This PR introduces the code directly in `processInbound()`, which is very close to how it's done in `go-nats`.

### CODE REVIEW

**Comment by aricart** [comment]
@andriy-bulynko I have the same comments as the other PR. We don't use Promises on node-nats.

**Comment by andriy-bulynko** [comment]
@aricart: Ok, thanks. Just to be clear, is a callback approach like `tokenHandler(function(token, error){})` also off limits?

**Comment by aricart** [comment]
@andriy-bulynko `tokenHandler(function(error, token)` would be fine. Just no Promise related code.

**Comment by andriy-bulynko** [comment]
@aricart: Promises are out. Asynchronous callbacks are in.

**Comment by andriy-bulynko** [comment]
Is this a problem with code or with build? Is there a way to kick the build to try again?

**Comment by andriy-bulynko** [comment]
That's so weird. I just re-ran the tests on repeat a bunch of times and nothing failed.

**Comment by andriy-bulynko** [comment]
There might be CI issues going on now...

**Comment by aricart** [comment]
replaced with the sync version

**Pull request closed without merging**
