### PR TITLE
addresses issue 97

### PR DESCRIPTION
**Pull request by sfrooster**
see #97

### CODE REVIEW

**Comment by derekcollison** [comment]
Be good to have some tests to prove it works correctly. Also check why tests failed.

**Comment by sfrooster** [comment]
I fixed he original round of failures, current failure only occurs with
Node6:

  1) Yield should yield to other events:

     Uncaught AssertionError: expected 21 to be within 10..20

      at Assertion.fail (node_modules/should/cjs/should.js:205:17)

      at Assertion.value [as within] (node_modules/should/cjs/should.js:277:19)

      at Timeout.<anonymous> (test/yield.js:33:20)


Don't know what that is.  As for a new test, my question is what behavior
would be inline with a timeout from the other clients?

**Comment by derekcollison** [comment]
That failure may be an anomaly. The testing framework allows for async testing, so we should add in a test that passes only if the request times out within the right amount of time.

**Comment by derekcollison** [comment]
Let me know when you add in the tests. If you could also rebase with master (not required) that would be great.

**Comment by sfrooster** [comment]
Tried writing mocha tests to catch async errors thrown and treat as success - no luck.

**Comment by sfrooster** [comment]
looks like there are other ways to tackle this in node

**Comment by aricart** [comment]
The correct is way is https://github.com/nats-io/node-nats/issues/97

**Pull request closed without merging**
