### PR TITLE
Fixed buffer concatentation

### PR DESCRIPTION
**Pull request by abstractvector**
Fixing the Buffer concatenation to avoid character encoding issues, as per #6

### CODE REVIEW

**Comment by abstractvector** [comment]
It's not a case of a performance impact - the functionality before wasn't working, and now it is.

**Comment by derekcollison** [comment]
Did you check why the tests failed?

**Comment by derekcollison** [comment]
Looks like the tests got broken, so we need to fix that..

**Comment by derekcollison** [comment]
There is a utf8 test which works correctly as is (at least under 0.10 & 12).. Does not need Buffer.concat.

**Pull request closed without merging**
