### PR TITLE
[FIX] #233 - if the client handler throws an exception, the library is possibly left in an inconsistent state.

### PR DESCRIPTION
**Pull request by aricart**

### CODE REVIEW

**Comment by StarpTech** [comment]
How do you want to fix it with `set Immediate` I don't get it. I also don't like this solution because as @valichek said the client should not responsible for user space errors. In worst case the application will exit and restarted. Do I miss something or isn't this the case?

**Comment by valichek** [comment]
@StarpTech smth like 
```
// msg is already local variable, so we set only these for closure
var reply = this.payload.reply;
var subj = this.payload.subj;
var sid = this.payload.sid;
var cb = function() {
    sub.callback(msg, reply, subj, sid);
}
setImmediate(cb);
```

**Comment by StarpTech** [comment]
@valichek as I asked before what do you expect? The process will still crash. Do you want to save inbound messages?

**Comment by valichek** [comment]
@StarpTech the first - is that this will result inbound buffer parsing to finish with consistent state and thrown error will not affect other messages - so it will not stop at this line https://github.com/nats-io/node-nats/blob/master/lib/nats.js#L971, another thing is that callbacks will be executed in async - not one by one from single flow like now.

**Comment by valichek** [comment]
@StarpTech  it's important to keep inbound buffer consistent, because next call of `processInbound` can be executed before crash

**Comment by StarpTech** [comment]
@valichek thanks for clarification now it's clear for me.

> it's important to keep inbound buffer consistent, because next call of processInbound can be executed before crash

What's the benefit of this? Even though we delay the execution to the next tick the first uncaught error will crash the process and all other callback have no chance to complete. You left your application in a broken state and you shouldn't expect nothing.

**Comment by valichek** [comment]
@StarpTech exception does not always result in crash, you can handle exceptions at very high level and decide how to proceed, for more example you can check https://stackoverflow.com/questions/7310521/node-js-best-practice-exception-handling

**Comment by StarpTech** [comment]
@valichek but this is not what your issue is about. If use `try/catch` you can always handle it anyway. Your proposal was to add `setImmediate` which IMO doesn't help here.

**Comment by valichek** [comment]
Btw: that browser js app never crashes, so it will definitely go to inconsistent state without any chance to proceed normally

**Comment by StarpTech** [comment]
This library is for server-side only.

**Comment by valichek** [comment]
@StarpTech actually, when you handle errors on higher levels of app and decide not to crash, `setImmediate()` will help, because exception will effect only to the current callback

**Comment by valichek** [comment]
@StarpTech what about https://nodejs.org/api/process.html#process_event_uncaughtexception ?

**Comment by StarpTech** [comment]
This is an anti-pattern. Read the `warning` description 😄

**Comment by valichek** [comment]
@StarpTech warning say nothing about being anti-pattern, sure one should take care about what he is doing

**Comment by StarpTech** [comment]
Exactly and in this case it's an antipattern because you wanna use it as a global catch handler not to gracefully shutdown your application.

**Comment by aricart** [comment]
> re-emitting caught error seems not good solution to me, because error doesn't belong to the library, but to the user code, using `setImmediate()` would be better solution, even if you loose a part of stack trace - it will be just nats related lines, btw `setImmediate()` is already used, so in some cases stack trace will not contain even a caller of `processInbound()`

`setImmediate` doesn't work. It happens when the event loop returns, which is when the inbound buffer is drained.

**Comment by StarpTech** [comment]
@aricart please consider this change as a breaking change because with this change user errors are swallowed when someone registered the `error` handler to listens only for NATS errors 😟

**Comment by aricart** [comment]
@StarpTech there's no api guarantee that the error you get from the the `error` handler is a NATSError. In the case where we raise the error, they will always be. This is already an user exception that is not handled.

**Pull request merged**
