### PR TITLE
Adding assignOption to port fixes #19

### LINKED ISSUE #19: Cannot Specify External Connection
When I try to do:
```
nats.connect({
    url: '127.0.0.1',
    port: '4222'
  });
```

I get:
```
TypeError: port should be a number or string: null
    at Socket.connect (net.js:914:13)
    at Object.exports.connect.exports.createConnection (net.js:92:35)
```

It looks like there is no default for opts.port and opts.port is not being assigned as an option.

### PR DESCRIPTION
**Pull request by dlabey**

### CODE REVIEW

**Comment by derekcollison** [comment]
If the url properly has a port and you specify one separately, does that override? Should we have a quick test to confirm that behavior?

**Comment by dlabey** [comment]
I can specify one in the url so this is not as bad as I thought. Would it hurt though to allow the port to be specified in the options though?

**Comment by derekcollison** [comment]
Again if they are specified in both places who wins?

**Comment by dlabey** [comment]
Ah yes I see now.

**Pull request closed without merging**
